<a href="https://colab.research.google.com/github/sahoosk/practicejavaproject/blob/master/Copy_of_MyProjectCarPredictionWithSeparteTestFile_submitted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Required Libraries**

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Lasso
from math import sqrt
from sklearn import metrics

**Importing Dataset**

In [9]:
dataset = pd.read_csv('/content/Training_Data_Set.csv')
dataset = dataset.set_index('Id')
dataset.fillna(0, inplace = True)
dataset.replace([np.inf, -np.inf], np.nan, inplace = True)

#Encoding non string values to numerical values
dataset.replace({'seat_count': {'None':0}}, inplace = True)
dataset.replace({'door_count': {'None':0}}, inplace = True)
dataset.replace({'body_type': {'compact':1, 'van':2}}, inplace = True)
dataset.replace({'fuel_type': {'petrol':1, 'diesel':2}}, inplace = True)
dataset.replace({'transmission': {'auto':1, 'man':2}}, inplace = True)

X = dataset.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]].values
Y = dataset.iloc[:,[15]].values

In [10]:
print(X)

[['skoda' 'octavia' 'Ahmedabad' ... 0 0 1]
 ['fiat' 'panda' 'Ahmedabad' ... '4' '4' 1]
 ['bmw' 'x1' 'Hyderabad' ... '4' '5' 2]
 ...
 ['bmw' 'x1' 'Pune' ... '4' '5' 2]
 ['toyota' 'avensis' 'Jaipur' ... 0 0 2]
 ['bmw' 'x5' 'Kochi' ... '5' '5' 2]]


In [11]:
print(Y)

[[ 543764.25]
 [ 401819.25]
 [2392855.5 ]
 ...
 [2008123.5 ]
 [ 874352.25]
 [1576610.25]]


In [12]:
Y.shape

(53515, 1)

In [13]:
dataset.head()

Maker    model   Location  Distance       Owner Type  \
Id                                                             
25001   skoda  octavia  Ahmedabad        0.0          Second   
25002    fiat    panda  Ahmedabad    27750.0           Third   
25003     bmw       x1  Hyderabad    46000.0           Third   
25004  nissan     juke     Mumbai    43949.0           Third   
25005     bmw       x5     Jaipur    59524.0  Fourth & Above   

       manufacture_year  Age of car  engine_displacement  engine_power  \
Id                                                                       
25001              1964          55                 1964         147.0   
25002              2012           7                 1242          51.0   
25003              2014           5                 1995         105.0   
25004              2011           8                 1618         140.0   
25005              2012           7                 2993         180.0   

       body_type  Vroom Audit Rating  transmission door_count seat_count  \
Id                                                                         
25001          1                   8             2          0          0   
25002          0                   6             2          4          4   
25003          0                   7             1          4          5   
25004          0                   7             2          4          5   
25005          0                   7             1          4          5   

       fuel_type       Price  
Id                            
25001          1   543764.25  
25002          1   401819.25  
25003          2  2392855.50  
25004          1   958606.50  
25005          2  3085561.50

In [14]:
dataset.isnull().sum()

Maker                  0
model                  0
Location               0
Distance               0
Owner Type             0
manufacture_year       0
Age of car             0
engine_displacement    0
engine_power           0
body_type              0
Vroom Audit Rating     0
transmission           0
door_count             0
seat_count             0
fuel_type              0
Price                  0
dtype: int64

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53515 entries, 25001 to 78515
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Maker                53515 non-null  object 
 1   model                53515 non-null  object 
 2   Location             53515 non-null  object 
 3   Distance             53515 non-null  float64
 4   Owner Type           53515 non-null  object 
 5   manufacture_year     53515 non-null  int64  
 6   Age of car           53515 non-null  int64  
 7   engine_displacement  53515 non-null  int64  
 8   engine_power         53515 non-null  float64
 9   body_type            53515 non-null  int64  
 10  Vroom Audit Rating   53515 non-null  int64  
 11  transmission         53515 non-null  int64  
 12  door_count           53515 non-null  object 
 13  seat_count           53515 non-null  object 
 14  fuel_type            53515 non-null  int64  
 15  Price                53515 non-n

# **Data Processing**

## ***Level Encoding***

In [16]:
from sklearn.preprocessing import LabelEncoder
leMaker = LabelEncoder()
X[:, 0] = leMaker.fit_transform(X[:, 0])
leModel = LabelEncoder()
X[:, 1] = leModel.fit_transform(X[:, 1])
leLocation = LabelEncoder()
X[:, 2] = leLocation.fit_transform(X[:, 2])
leOwnerType = LabelEncoder()
X[:, 4] = leOwnerType.fit_transform(X[:, 4])



In [ ]:
#from sklearn.preprocessing import OneHotEncoder
#from sklearn.compose import ColumnTransformer
#ctTransmission = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [11])], remainder = 'passthrough')
#X = ctTransmission.fit_transform(X)
#ctFuelType = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [14])], remainder = 'passthrough')
#X = ctFuelType.fit_transform(X)


In [17]:
print(X)

[[6 8 0 ... 0 0 1]
 [2 9 0 ... '4' '4' 1]
 [1 18 5 ... '4' '5' 2]
 ...
 [1 18 10 ... '4' '5' 2]
 [7 1 6 ... 0 0 2]
 [1 20 7 ... '5' '5' 2]]


# Feature Scaling

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)


In [19]:
print(X)

[[ 0.67044115 -0.52537891 -1.58682764 ... -2.21242654 -2.20874584
  -1.0304166 ]
 [-0.89516732 -0.36322156 -1.58682764 ...  0.37999873 -0.05860016
  -1.0304166 ]
 [-1.28656944  1.09619461 -0.00308964 ...  0.37999873  0.47893626
   0.97048126]
 ...
 [-1.28656944  1.09619461  1.58064835 ...  0.37999873  0.47893626
   0.97048126]
 [ 1.06184326 -1.66048038  0.31365796 ... -2.21242654 -2.20874584
   0.97048126]
 [-1.28656944  1.42050931  0.63040556 ...  1.02810505  0.47893626
   0.97048126]]


# Splitting dataset into Training and Testing set

In [20]:
from sklearn.model_selection import train_test_split
(X_train, X_test, Y_train, Y_test) = train_test_split(X, Y, test_size = 0.2, random_state = 0)


# Training Model

In [21]:
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state = 0)
regression.fit(X_train, Y_train)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(random_state=0)

In [22]:
y_pred = regression.predict(X_test)

In [23]:
print(y_pred)

[1295843.37  2228081.775 2267860.395 ...  912681.465 1897356.48
  406650.69 ]


In [24]:
print(Y_test)

[[1291398.75]
 [2065961.25]
 [2080148.25]
 ...
 [1012500.  ]
 [1626134.25]
 [ 360843.75]]


# Testing Result

In [25]:
mydata = np.concatenate((y_pred.reshape(len(y_pred), 1), Y_test.reshape(len(Y_test), 1)), 1)
print(mydata)

[[1295843.37  1291398.75 ]
 [2228081.775 2065961.25 ]
 [2267860.395 2080148.25 ]
 ...
 [ 912681.465 1012500.   ]
 [1897356.48  1626134.25 ]
 [ 406650.69   360843.75 ]]


# Calculating Accuracy of model

In [26]:
from sklearn.metrics import r2_score
r2_score(Y_test, y_pred)



0.9298218070105091

# Making a Dataframe

In [ ]:
dataframe = pd.DataFrame(mydata,columns = ['Predicted Value', 'Real Value'])
print(dataframe)

       Predicted Value  Real Value
0         1.295843e+06  1291398.75
1         2.228082e+06  2065961.25
2         2.267860e+06  2080148.25
3         1.088798e+06  1128141.75
4         4.960416e+05   450199.50
...                ...         ...
10698     5.553686e+06  5480837.25
10699     2.118760e+06  2113512.00
10700     9.126815e+05  1012500.00
10701     1.897356e+06  1626134.25
10702     4.066507e+05   360843.75

[10703 rows x 2 columns]


In [ ]:
dataframe.to_csv

<bound method NDFrame.to_csv of        Predicted Value  Real Value
0         1.295843e+06  1291398.75
1         2.228082e+06  2065961.25
2         2.267860e+06  2080148.25
3         1.088798e+06  1128141.75
4         4.960416e+05   450199.50
...                ...         ...
10698     5.553686e+06  5480837.25
10699     2.118760e+06  2113512.00
10700     9.126815e+05  1012500.00
10701     1.897356e+06  1626134.25
10702     4.066507e+05   360843.75

[10703 rows x 2 columns]>

In [ ]:
print(dataframe.index)

RangeIndex(start=0, stop=10703, step=1)


In [ ]:
dataframe.to_csv(r'/content/my_data_export.csv', index=True)

# Prepare External Test Data set to feed the Trained Model

In [62]:
import pandas as pdExt
external_dataset = pdExt.read_csv('/content/Test_Data_Set.csv')
external_dataset = external_dataset.set_index('Id')
external_dataset.fillna(0, inplace = True)

import numpy as npExt
external_dataset.replace([npExt.inf, -npExt.inf], npExt.nan, inplace = True)

#Encoding non string values to numerical values
external_dataset.replace({'seat_count': {'None':0}}, inplace = True)
external_dataset.replace({'door_count': {'None':0}}, inplace = True)
external_dataset.replace({'body_type': {'compact':1, 'van':2}}, inplace = True)
external_dataset.replace({'fuel_type': {'petrol':1, 'diesel':2}}, inplace = True)
external_dataset.replace({'transmission': {'auto':1, 'man':2}}, inplace = True)

X_external_dataset = external_dataset.iloc[:, [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]].values

from sklearn.preprocessing import LabelEncoder
leMaker = LabelEncoder()
X_external_dataset[:, 0] = leMaker.fit_transform(X_external_dataset[:, 0])
leModel = LabelEncoder()
X_external_dataset[:, 1] = leModel.fit_transform(X_external_dataset[:, 1])
leLocation = LabelEncoder()
X_external_dataset[:, 2] = leLocation.fit_transform(X_external_dataset[:, 2])
leOwnerType = LabelEncoder()
X_external_dataset[:, 4] = leOwnerType.fit_transform(X_external_dataset[:, 4])

from sklearn.preprocessing import StandardScaler
scExternal = StandardScaler()
X_external_dataset = scExternal.fit_transform(X_external_dataset)

In [63]:
print(X_external_dataset)

[[ 0.65706126 -0.50942244  1.27807864 ...  0.38301867  0.47958219
  -1.02726378]
 [ 0.65706126  0.4691636  -0.62186706 ...  0.38301867  0.47958219
   0.97345981]
 [ 0.65706126 -0.50942244 -0.62186706 ...  1.0292476   0.47958219
   0.97345981]
 ...
 [ 0.65706126 -0.50942244 -1.25518229 ...  1.0292476   0.47958219
   0.97345981]
 [ 0.26196606  0.30606593  0.32810579 ...  0.38301867  1.55693926
  -1.02726378]
 [-0.52822434 -0.99871546  0.32810579 ... -2.20189702 -2.21381049
  -1.02726378]]


In [64]:

y_pred_extTernal_dataset = regression.predict(X_external_dataset)

In [65]:
print(y_pred_extTernal_dataset)
print(len(y_pred_extTernal_dataset))
print(len(X_external_dataset))


[ 419854.605   996192.48   1426099.2975 ...  388487.1525 1118351.1825
  775639.0725]
5615
5615


In [67]:
import numpy as npExt2
#myExtdata = npExt2.concatenate((y_pred_extTernal_dataset.reshape(len(y_pred_extTernal_dataset), 1), X_external_dataset.reshape(len(X_external_dataset), 1)), 1)
myExtdata = npExt2.concatenate((X_external_dataset.reshape(len(X_external_dataset), 15), y_pred_extTernal_dataset.reshape(len(y_pred_extTernal_dataset), 1)), 1)
print(myExtdata)

dataframeExt = pd.DataFrame(myExtdata)
print(dataframeExt)
dataframeExt.to_csv(r'/content/my_data_export.csv', index=True)



[[ 6.57061258e-01 -5.09422441e-01  1.27807864e+00 ...  4.79582191e-01
  -1.02726378e+00  4.19854605e+05]
 [ 6.57061258e-01  4.69163603e-01 -6.21867057e-01 ...  4.79582191e-01
   9.73459811e-01  9.96192480e+05]
 [ 6.57061258e-01 -5.09422441e-01 -6.21867057e-01 ...  4.79582191e-01
   9.73459811e-01  1.42609930e+06]
 ...
 [ 6.57061258e-01 -5.09422441e-01 -1.25518229e+00 ...  4.79582191e-01
   9.73459811e-01  3.88487153e+05]
 [ 2.61966060e-01  3.06065929e-01  3.28105789e-01 ...  1.55693926e+00
  -1.02726378e+00  1.11835118e+06]
 [-5.28224338e-01 -9.98715463e-01  3.28105789e-01 ... -2.21381049e+00
  -1.02726378e+00  7.75639073e+05]]
            0         1         2         3         4         5         6   \
0     0.657061 -0.509422  1.278079  0.184201 -1.302263 -0.736289  0.736289   
1     0.657061  0.469164 -0.621867 -0.210483  1.345488  0.741516 -0.741516   
2     0.657061 -0.509422 -0.621867 -0.206599  0.462905  0.741516 -0.741516   
3    -1.713510 -0.183227 -0.305209 -0.278299 -0.4196